export const themes = {
  normal: {
    background: '#FFFFFF',
    surface: '#F8F9FA',
    surfaceElevated: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    primary: '#4ECDC4',
    primaryText: '#FFFFFF',
    danger: '#EF4444',
    success: '#22C55E',
    warning: '#F59E0B',
    tabBar: '#FFFFFF',
    tabBarBorder: '#E5E7EB',
    tabBarActive: '#4ECDC4',
    tabBarInactive: '#9CA3AF',
    card: '#FFFFFF',
    cardBorder: '#F3F4F6',
    inputBackground: '#F9FAFB',
    inputBorder: '#D1D5DB',
    shadow: 'rgba(0, 0, 0, 0.08)',
    // Categorias
    cotidianas: '#4ECDC4',
    trabajo: '#FFB347',
    social: '#B19CD9',
    salud: '#77DD77',
    // Accesibilidad
    fontSize: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 18,
      xl: 22,
      xxl: 28,
      hero: 34,
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 24,
      xxl: 32,
    },
    borderRadius: {
      sm: 8,
      md: 12,
      lg: 16,
      xl: 24,
      full: 9999,
    },
    animationDuration: 200,
  },
  calma: {
    background: '#F5F0EB',
    surface: '#FAF7F4',
    surfaceElevated: '#FFFFFF',
    text: '#3D3429',
    textSecondary: '#7A7067',
    textMuted: '#A89E94',
    border: '#E8E0D8',
    primary: '#A8DDD9',
    primaryText: '#3D3429',
    danger: '#E8A0A0',
    success: '#A0D8A0',
    warning: '#E8C880',
    tabBar: '#FAF7F4',
    tabBarBorder: '#E8E0D8',
    tabBarActive: '#A8DDD9',
    tabBarInactive: '#A89E94',
    card: '#FFFFFF',
    cardBorder: '#EDE7E0',
    inputBackground: '#FAF7F4',
    inputBorder: '#DDD5CC',
    shadow: 'rgba(61, 52, 41, 0.05)',
    // Categorias (desaturadas)
    cotidianas: '#A8DDD9',
    trabajo: '#FFDBA8',
    social: '#D4CBE8',
    salud: '#B8EBB8',
    // Accesibilidad - tipografia mas grande, mas espaciado
    fontSize: {
      xs: 14,
      sm: 16,
      base: 18,
      lg: 20,
      xl: 24,
      xxl: 30,
      hero: 36,
    },
    spacing: {
      xs: 6,
      sm: 10,
      md: 16,
      lg: 20,
      xl: 28,
      xxl: 36,
    },
    borderRadius: {
      sm: 12,
      md: 16,
      lg: 20,
      xl: 28,
      full: 9999,
    },
    animationDuration: 400, // 2x mas lento
  },
} as const;

export type ThemeMode = keyof typeof themes;
export type Theme = (typeof themes)[ThemeMode];
